### ISSUE TITLE
Reset Search Broken

### ISSUE THREAD

**Issue by mattrhoden** [daniellersisk/todoMotley#2]
Looking at this todo project, the reset search button was broken. 

The reason seems to be pretty straight forward; when the `resetSearchBar` function is invoked, you are passing in the full list of todo items to be set as the search result. This causes the list to briefly appear. 

Since your button is set to `type="submit"` this would normally mean you're trying to do a HTTP Post request with a form. However, the default action when no form element exist is a HTTP GET request. The overall effect is the page refreshes. 

After the page is refreshed, the entire page is redrawn and results appear to clear out. 

> :information_source: To discover this, you can use the chrome developer tools and utilize the network tab with preserve logs turned on. You can also set breakpoints in the Sources tab and step through your code to see how this activity unfolds and verify assumptions.

All said and done, you should update `resetSearchBar` from this:

```javascript
    const resetSearchBar = ()=>{ // resetting seach bar back to all todos
        setSearchedTodos(todos)
    }
```

to this:

```javascript
    const resetSearchBar = (e)=>{ // resetting seach bar back to all todos
        setSearchedTodos([]);
    }
```

and update the button type from this:

```jsx
      <button onClick={resetSearchBar} type="submit">
        Reset Search
      </button>
```

to this:

```jsx
      <button onClick={resetSearchBar} type="button">
        Reset Search
      </button>
```

**Comment by daniellersisk** [comment]
Thank you!
